#ifndef __LEVEL_MODEL_DEFINITIONS_H__
#define __LEVEL_MODEL_DEFINITIONS_H__

enum MapPosition {
    EMPTY_CAN_PUT, // 0
    ENEMY_PATH, // 1
    ENEMY_PATH_END, // 2
    EMPTY_CANNOT_PUT, // 3
    EMPTY_CAN_PUT_OCCUPIED, // 4
    ENEMY_PATH_OCCUPIED // 5
};

#define UPDATING_FREQUENCY 0.01
#define ACCEPTING_TIME_ERROR 0.0001
#define DUMP_CAPACITY 100

#define MAX_ENERGY 9000
#define MAX_GOLD 999990

#endif // !__LEVEL_MODEL_DEFINITIONS_H__