#ifndef __CELL_MODEL_DEFINITIONS_H__
#define __CELL_MODEL_DEFINITIONS_H__

enum CellId {
    CELL_00_EOSINOPHILS,
    CELL_01_ERYTHROCYTES,
    CELL_02_PLATELETS,
    CELL_03_BASOPHILS,
    CELL_04_MONOCYTES
};

#endif // !__CELL_MODEL_DEFINITIONS_H__