#ifndef __PROJECTILE_MODEL_DEFINITIONS_H__
#define __PROJECTILE_MODEL_DEFINITIONS_H__

enum ProjectileId {
    CELL_00_PROJECTILE,
    CELL_03_PROJECTILE,
    CELL_05_PROJECTILE
};

#endif // !__PROJECTILE_MODEL_DEFINITIONS_H__