#ifndef __UI_CONTROL_ENERGY_DEFINITIONS_H__
#define __UI_CONTROL_ENERGY_DEFINITIONS_H__

#define ENERGY_LAYER_ZORDER 10
#define CELL_WIDTH 98.0f
#define POS_X_ORIGIN 360.0f + CELL_WIDTH / 2.0f
#define POS_Y_ORIGIN 110.0f + CELL_WIDTH / 2.0f

#define IMG_ENERGY "sprites/objects/pickup/energy.png"

#define ANIM_ENERGY_POPUP_DURATION 0.5f
#define ANIM_ENERGY_DESTROY_DURATION 0.4f

#endif // !__UI_CONTROL_ENERGY_DEFINITIONS_H__