#ifndef __UI_OBJECTS_DEFINITIONS_H__
#define __UI_OBJECTS_DEFINITIONS_H__

#define CELL_WIDTH 98.0f
#define POS_X_ORIGIN 360.0f + CELL_WIDTH / 2.0f
#define POS_Y_ORIGIN 110.0f + CELL_WIDTH / 2.0f

#endif // !__UI_OBJECTS_DEFINITIONS_H__